### ISSUE TITLE
Segwit support and importing time/size

### ISSUE THREAD

**Issue by brunoaduarte** [haw-itn/bitcoin2graphdb#4]
Hi @azuchi and @sgtakeru  !

Are there any limitations to this tool regarding SEGWIT support ?

Also, do you have an estimate on how big will the final Neo4j database size be and how long would it take to import the current (562002) blocks?

Thanks!

**Comment by azuchi** [comment]
Hi @brunoaduarte, 

bitcoin2graphdb can already parse a Segwit transaction.

Unfortunately this tool does not make the mainnet synchronization in time.

**Comment by brunoaduarte** [comment]
> Hi @brunoaduarte,
> 
> bitcoin2graphdb can already parse a Segwit transaction.
> 
> Unfortunately this tool does not make the mainnet synchronization in time.

Thanks @azuchi . Why not ?

**Comment by azuchi** [comment]
@brunoaduarte mainnet has nearly 1MB block, it takes time to import the block, so the import will not make it in time. For this, it is possible to change the method of importing blocks to parse RAW block instead of RPC.  However, apart from that, I think that the performance in importing Neo4j and data query will be a bottleneck.
